version: '2.4'
services:
    cb:
        image: "couchbase:enterprise-6.0.1"
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 8094:8094
            - 8095:8095
            - 11210:11210
    jaeger:
        build: .
        environment:
            - COUCHBASE_USERNAME=Administrator
            - COUCHBASE_PASSWORD=password
            - COUCHBASE_BUCKET=default
            - COUCHBASE_CONNSTRING=couchbase://cb
            - COUCHBASE_AUTOSETUP=true
            - COUCHBASE_N1QLFALLBACK=false
            - COUCHBASE_USEANALYTICS=true
            - GRPC_VERBOSITY=DEBUG
            - GRPC_TRACE=all
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
        depends_on:
             - cb

